//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TDSAlmaxarifado.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Colaborador
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Colaborador()
        {
            this.SAIDA = new HashSet<SAIDA>();
        }
    
        public int colid { get; set; }
        public string colnome { get; set; }
        public string colcargo { get; set; }
        public Nullable<int> Areid { get; set; }
    
        public virtual AREA AREA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SAIDA> SAIDA { get; set; }
    }
}
